In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import pickle  # to save the model


In [34]:
import sys
print(sys.executable)


/usr/local/bin/python3


In [35]:
!pip install --user scikit-learn==1.5.2


In [36]:
!pip list


Package                      Version
---------------------------- ------------
absl-py                      2.1.0
appnope                      0.1.3
asn1crypto                   1.5.1
asttokens                    2.2.1
astunparse                   1.6.3
attrs                        24.2.0
Babel                        2.10.3
backcall                     0.2.0
beautifulsoup4               4.12.3
blinker                      1.8.2
cachetools                   5.3.3
cbor2                        5.4.2
certifi                      2024.2.2
cffi                         1.17.1
chardet                      5.2.0
charset-normalizer           3.3.2
cicflowmeter                 0.2.0
click                        8.1.7
comm                         0.1.3
contourpy                    1.0.7
cryptography                 3.4.8
cycler                       0.11.0
debugpy                      1.6.7
decorator                    5.1.1
docopt                       0.6.2
docutils                     0.20.1
et

In [37]:
!conda install scikit-learn=1.5.2


zsh:1: command not found: conda


In [38]:
import sklearn
print(sklearn.__file__)


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__init__.py


In [39]:
!pip cache purge


Files removed: 1435


In [40]:
!pip install scikit-learn==1.5.2


In [33]:
# Upgrade pip
!pip install --upgrade pip

# Uninstall the existing version
!pip uninstall scikit-learn -y

# Install the desired version
!pip install scikit-learn==1.5.2

# Verify the installation
import sklearn
print(sklearn.__version__)


Found existing installation: scikit-learn 1.5.2
Uninstalling scikit-learn-1.5.2:
  Successfully uninstalled scikit-learn-1.5.2
  Using cached scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl.metadata (13 kB)
Using cached scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl (11.0 MB)
1.2.2


In [50]:
!pip install scikit-learn==1.5.2


In [51]:
import sklearn
print(sklearn.__version__)


1.2.2


Load the dataset 

In [21]:
# Load dataset
train_data = pd.read_csv("train - train.csv")
test_data = pd.read_csv("test - test.csv")

# Separate features and target
X = train_data.drop("price_range", axis=1)
y = train_data["price_range"]

# Split into train and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

Train the model

In [22]:
from sklearn.impute import SimpleImputer


In [26]:

!pip install --upgrade pip


In [16]:
# Initialize the imputer to replace NaNs with the mean of each column
imputer = SimpleImputer(strategy='mean')
imputer.fit(X_train)
# Fit on training data and transform both train and validation sets
X_train = imputer.fit_transform(X_train)
X_val = imputer.transform(X_val)



In [ ]:
with open("imputer.pkl", "wb") as f:
    pickle.dump(imputer, f)

In [17]:
# Initialize the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Evaluate on validation set
y_pred = rf_model.predict(X_val)
accuracy = accuracy_score(y_val, y_pred)
print("Validation Accuracy:", accuracy)

# Confusion matrix
cm = confusion_matrix(y_val, y_pred)
print("Confusion Matrix:\n", cm)


Validation Accuracy: 0.9
Confusion Matrix:
 [[102   3   0   0]
 [  7  80   4   0]
 [  0   5  79   8]
 [  0   0  13  99]]


Test the Data in the Test dataset

In [15]:
# Inspect the test dataset
print("Test Data Columns:", test_data.columns)

# Drop columns that are not in the training dataset (if applicable)
# Ensure that you drop the target variable and any other unnecessary columns
# Assuming the training features were the same as the following:
training_features = ['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g', 
                      'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height', 
                      'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g', 
                     'touch_screen', 'wifi']

# Drop unnecessary columns, if they exist
X_test = test_data[training_features]  # Use the correct feature list from your training set

# Handle any missing values in the test data
# Make sure to have defined `imputer` from your training phase
X_test = imputer.transform(X_test)  # Use the same imputer fitted on the training data

# Now, predict price range categories for the test dataset
y_test_pred = rf_model.predict(X_test)

# Display the predictions
print("Predicted Price Ranges:", y_test_pred)


Test Data Columns: Index(['id', 'battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc',
       'four_g', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc',
       'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object')
Predicted Price Ranges: [3 3 2 3 1 3 3 1 3 0 3 3 0 0 2 0 2 1 3 2 1 3 1 1 3 0 2 0 2 0 2 0 3 0 1 1 3
 1 2 1 1 2 0 0 0 1 0 3 1 2 1 0 3 0 3 1 3 1 1 3 3 2 0 1 1 1 1 3 1 1 1 2 2 3
 3 0 2 0 2 3 0 3 3 0 3 0 3 1 3 0 1 2 2 0 2 2 0 2 1 2 1 0 0 3 1 2 1 1 2 3 3
 3 1 3 3 3 3 1 3 0 0 2 2 1 1 0 3 2 2 1 0 2 1 1 3 1 2 0 3 2 1 3 2 2 2 3 3 2
 2 3 2 3 0 0 3 2 3 3 3 3 2 2 3 3 3 3 1 0 3 0 0 0 1 0 0 1 0 0 1 2 0 0 0 1 2
 2 2 1 0 0 0 1 0 3 1 0 2 2 2 3 1 2 3 3 3 1 2 1 0 0 1 2 1 2 3 3 0 2 0 3 2 3
 3 0 0 1 0 3 0 1 0 2 2 1 3 0 2 0 3 1 2 0 0 2 1 3 3 3 1 1 3 0 0 2 3 3 1 3 1
 0 3 2 1 2 3 3 3 1 0 1 2 3 1 1 3 2 0 3 0 1 2 0 0 3 2 3 3 2 1 3 3 2 3 2 2 1
 1 0 2 3 1 0 0 3 0 3 0 1 2 0 2 2 1 3 1 2 1 2 0 0 0 1 3 1 0 0 0 3 1 0 3 3 1
 2 3 2 3

Save the Model

In [18]:
with open("rf_model.pkl", "wb") as f:
    pickle.dump(rf_model, f)
